### ISSUE TITLE
Not work in GlotPress 4.0.0

### ISSUE THREAD

**Issue by criconhelp** [toolstack/gp-project-contributors#2]
Please, update this plugin for GlotPress 4.0.0

**Comment by toolstack** [comment]
Are you seeing a specific error?  I have found an issue with the gp-project-contributors-translators shortcode, is that the issue you're seeing?

**Comment by criconhelp** [comment]
Please help me figure it out. I'm trying to display a list of translators in the project.

I updated the plugin after your changes today for GlotPress 4.0.0

I specified the code `[gp-project-contributors slug=mgs3sehd]` in the `wp-content\plugins\glotpress\gp-templates\project.php` template, 

![Снимок экрана 2024-03-31 211418](https://github.com/toolstack/gp-project-contributors/assets/32668356/7550fb43-02e7-4766-afeb-ad84a24f2a6d)

but nothing is displayed.

![Снимок экрана 2024-03-31 211359](https://github.com/toolstack/gp-project-contributors/assets/32668356/06de7079-4e9b-4f48-b93a-bfad1f712210)

**Comment by toolstack** [comment]
That won't work, you have to wrap the shortcode in a `do-shortcode()` call if you're calling it from the GP template instead of a WP post/page, try this:

`<?php echo do_shortcode( '[gp-project-contributors slug=mgs3sehd]' );?>`

**Comment by criconhelp** [comment]
Thank you for helping me figure out how to insert the code into the template.

After pasting, I got the following output on the page:
![Снимок экрана 2024-03-31 230627](https://github.com/toolstack/gp-project-contributors/assets/32668356/62f74f70-6ce9-4c21-863d-d1b09a2ce37d)

and the source code:
![Снимок экрана 2024-03-31 230517](https://github.com/toolstack/gp-project-contributors/assets/32668356/d09dce42-029a-41b6-ac67-c1bafff57d3c)

Does this plugin implement something similar to the one on the official website [translate.wordpress.org](https://translate.wordpress.org/locale/ru/default/wp/dev/)?
![Снимок экрана 2024-03-31 230533](https://github.com/toolstack/gp-project-contributors/assets/32668356/0fbfe505-9536-4030-8ab7-0ab90245cba8)

I asked a question [here in GlotPress](https://github.com/GlotPress/GlotPress/issues/1767), but I couldn’t figure out how to display this template in the same form.

**Comment by toolstack** [comment]
No, the format is much simpler, just a list of contributors and their translated count.
